<?php

declare(strict_types=1);

namespace App\TenantSiteSetup;

/**
 * Единый реестр пунктов для обзора, прогресса и guided-очереди: наращивается без переделки ядра.
 *
 * Состав «quick» / «extended» и доменных ключей отражает продуктовое покрытие на дату; весь кабинет ими не исчерпывается.
 */
final class SetupItemRegistry
{
    /**
     * @return array<string, SetupItemDefinition>
     */
    public static function definitions(): array
    {
        $items = [
            new SetupItemDefinition(
                key: 'settings.site_name',
                categoryKey: 'quick_launch',
                title: 'Название сайта',
                description: 'Как называется ваш проект в шапке и письмах.',
                importance: SetupItemImportance::Critical,
                sortOrder: 10,
                filamentRouteName: 'filament.admin.pages.settings',
                targetKind: SetupItemTargetKind::Field,
                targetKey: 'settings.site_name',
                targetLabel: 'Название сайта',
                prerequisiteKeys: [],
                skipAllowed: true,
                notNeededAllowed: false,
                launchCritical: true,
                profileDependencyKeys: [],
                completionRefreshTags: ['tenant_setting:general.site_name'],
                themeConstraints: null,
                featureConstraints: null,
                settingsTabKey: 'general',
                settingsSectionId: 'site_identity',
            ),
            new SetupItemDefinition(
                key: 'settings.logo',
                categoryKey: 'quick_launch',
                title: 'Логотип',
                description: 'Загрузите логотип для шапки сайта.',
                importance: SetupItemImportance::Recommended,
                sortOrder: 20,
                filamentRouteName: 'filament.admin.pages.settings',
                targetKind: SetupItemTargetKind::Field,
                targetKey: 'settings.logo',
                targetLabel: 'Логотип',
                prerequisiteKeys: [],
                skipAllowed: true,
                notNeededAllowed: true,
                launchCritical: false,
                profileDependencyKeys: [],
                completionRefreshTags: ['tenant_setting:branding.logo', 'tenant_setting:branding.logo_path'],
                themeConstraints: null,
                featureConstraints: null,
                settingsTabKey: 'appearance',
            ),
            new SetupItemDefinition(
                key: 'settings.tagline_or_short_description',
                categoryKey: 'quick_launch',
                title: 'Краткое описание',
                description: 'Короткий оффер или описание для посетителей.',
                importance: SetupItemImportance::Recommended,
                sortOrder: 30,
                filamentRouteName: 'filament.admin.pages.settings',
                targetKind: SetupItemTargetKind::Field,
                targetKey: 'settings.tagline_or_short_description',
                targetLabel: 'Краткое описание',
                prerequisiteKeys: [],
                skipAllowed: true,
                notNeededAllowed: true,
                launchCritical: false,
                profileDependencyKeys: [],
                completionRefreshTags: ['tenant_setting:general.short_description'],
                themeConstraints: null,
                featureConstraints: null,
                settingsTabKey: 'general',
                settingsSectionId: 'site_identity',
            ),
            new SetupItemDefinition(
                key: 'contact_channels.primary_phone',
                categoryKey: 'contacts',
                title: 'Основной телефон',
                description: 'Рабочий номер для связи с клиентами.',
                importance: SetupItemImportance::Critical,
                sortOrder: 10,
                filamentRouteName: 'filament.admin.pages.settings',
                targetKind: SetupItemTargetKind::Field,
                targetKey: 'contact_channels.primary_phone',
                targetLabel: 'Телефон',
                prerequisiteKeys: [],
                skipAllowed: true,
                notNeededAllowed: false,
                launchCritical: true,
                profileDependencyKeys: [],
                completionRefreshTags: ['tenant_setting:contacts.phone'],
                themeConstraints: null,
                featureConstraints: null,
                settingsTabKey: 'general',
                settingsSectionId: 'contacts_block',
            ),
            new SetupItemDefinition(
                key: 'contact_channels.preferred_contact_channel',
                categoryKey: 'contacts',
                title: 'Каналы для форм',
                description: 'Хотя бы два способа связи доступны как предпочтительные в формах (например телефон + мессенджер).',
                importance: SetupItemImportance::Recommended,
                sortOrder: 20,
                filamentRouteName: 'filament.admin.pages.contact-channels-page',
                targetKind: SetupItemTargetKind::Page,
                targetKey: 'contact_channels.preferred_contact_channel',
                targetLabel: 'Каналы связи',
                prerequisiteKeys: [],
                skipAllowed: true,
                notNeededAllowed: true,
                launchCritical: false,
                profileDependencyKeys: [],
                completionRefreshTags: ['tenant_setting:contact_channels.state'],
                themeConstraints: null,
                featureConstraints: null,
            ),
            new SetupItemDefinition(
                key: 'programs.first_published_program',
                categoryKey: 'programs',
                title: 'Первая программа',
                description: 'Опубликованная программа с названием и описанием.',
                importance: SetupItemImportance::Critical,
                sortOrder: 10,
                filamentRouteName: 'filament.admin.resources.tenant-service-programs.index',
                targetKind: SetupItemTargetKind::Action,
                targetKey: 'programs.create_action',
                targetLabel: 'Создать программу',
                prerequisiteKeys: [],
                skipAllowed: true,
                notNeededAllowed: false,
                launchCritical: true,
                profileDependencyKeys: [],
                completionRefreshTags: ['resource:programs'],
                themeConstraints: ['expert_auto'],
                featureConstraints: null,
                targetFallbackKeys: ['programs.program_form'],
            ),
            new SetupItemDefinition(
                key: 'pages.home.hero_title',
                categoryKey: 'content',
                title: 'Заголовок главной (hero)',
                description: 'Заполните заголовок в блоке Hero на главной странице.',
                importance: SetupItemImportance::Critical,
                sortOrder: 10,
                filamentRouteName: null,
                targetKind: SetupItemTargetKind::Field,
                targetKey: 'pages.home.hero_title',
                targetLabel: 'Заголовок hero',
                prerequisiteKeys: [],
                skipAllowed: true,
                notNeededAllowed: false,
                launchCritical: true,
                profileDependencyKeys: [],
                completionRefreshTags: ['page:home'],
                themeConstraints: null,
                featureConstraints: null,
                pageBuilderFallbackSectionTypeIds: ['hero'],
                fallbackSetupAction: 'pages.home.add_block',
            ),
            new SetupItemDefinition(
                key: 'settings.favicon',
                categoryKey: 'extended',
                title: 'Иконка сайта (favicon)',
                description: 'Загрузите favicon для вкладки браузера и закладок.',
                importance: SetupItemImportance::Recommended,
                sortOrder: 100,
                filamentRouteName: 'filament.admin.pages.settings',
                targetKind: SetupItemTargetKind::Field,
                targetKey: 'settings.favicon',
                targetLabel: 'Favicon',
                prerequisiteKeys: [],
                skipAllowed: true,
                notNeededAllowed: true,
                launchCritical: false,
                profileDependencyKeys: [],
                completionRefreshTags: ['tenant_setting:branding.favicon', 'tenant_setting:branding.favicon_path'],
                themeConstraints: null,
                featureConstraints: null,
                settingsTabKey: 'appearance',
                settingsSectionId: 'branding_favicon',
                readinessTier: SetupReadinessTier::Extended,
            ),
            new SetupItemDefinition(
                key: 'settings.analytics_counters',
                categoryKey: 'extended',
                title: 'Аналитика',
                description: 'Подключите Яндекс Метрику и/или GA4 по ID.',
                importance: SetupItemImportance::Recommended,
                sortOrder: 110,
                filamentRouteName: 'filament.admin.pages.settings',
                targetKind: SetupItemTargetKind::Field,
                targetKey: 'settings.analytics_yandex_ga',
                targetLabel: 'Счётчики аналитики',
                prerequisiteKeys: [],
                skipAllowed: true,
                notNeededAllowed: true,
                launchCritical: false,
                profileDependencyKeys: [],
                completionRefreshTags: ['tenant_setting:integrations.analytics'],
                themeConstraints: null,
                featureConstraints: null,
                settingsTabKey: 'analytics',
                readinessTier: SetupReadinessTier::Extended,
            ),
            new SetupItemDefinition(
                key: 'pages.home.hero_cta_or_contact_block',
                categoryKey: 'content',
                title: 'Призыв или контакты на главной',
                description: 'Добавьте блок CTA, форму заявки или контакты.',
                importance: SetupItemImportance::Critical,
                sortOrder: 20,
                filamentRouteName: null,
                targetKind: SetupItemTargetKind::Section,
                targetKey: 'pages.home.hero_cta_or_contact_block',
                targetLabel: 'Блок CTA / контакты',
                prerequisiteKeys: [],
                skipAllowed: true,
                notNeededAllowed: false,
                launchCritical: true,
                profileDependencyKeys: [],
                completionRefreshTags: ['page:home'],
                themeConstraints: null,
                featureConstraints: null,
                pageBuilderFallbackSectionTypeIds: ['cta', 'expert_lead_form', 'contacts_info', 'contact_inquiry'],
                fallbackSetupAction: 'pages.home.add_block',
            ),
        ];

        $map = [];
        foreach ($items as $item) {
            $map[$item->key] = $item;
        }

        return $map;
    }
}
